version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - 127.0.0.1:9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - "node.name=es01"
      - "cluster.name=es-docker-cluster"
      - "cluster.initial_master_nodes=es01"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - es-data:/usr/share/elasticsearch/data

    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic: {}

volumes:
  es-data:
    driver: local